# Generated by Django 4.1.3 on 2022-11-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronym', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('phone', models.IntegerField()),
                ('subdivision', models.CharField(max_length=150)),
                ('photo_employee', models.ImageField(null=True, upload_to='')),
                ('profession', models.TextField()),
            ],
            options={
                'verbose_name': 'Работники',
                'verbose_name_plural': 'Работник',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_medicine', models.ImageField(upload_to='')),
                ('date_medicine', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.employee')),
            ],
            options={
                'verbose_name': 'Мед.заключения',
                'verbose_name_plural': 'Мед.заключение',
            },
        ),
        migrations.CreateModel(
            name='Psycho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_finish_psycho', models.DateField()),
                ('date_end_psycho', models.DateField()),
                ('photo_psycho', models.ImageField(upload_to='')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.employee')),
            ],
            options={
                'verbose_name': 'Псих.освидетельствования',
                'verbose_name_plural': 'Псих.освидетельстование',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('number', models.IntegerField()),
                ('date_of_issue', models.DateField()),
                ('fms', models.TextField()),
                ('registration', models.TextField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.employee')),
            ],
            options={
                'verbose_name': 'Паспорта',
                'verbose_name_plural': 'Паспорт',
            },
        ),
        migrations.CreateModel(
            name='MedicineParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_paragraph', models.IntegerField()),
                ('date_finish_paragraph', models.DateField()),
                ('date_end_paragraph', models.DateField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.medicine')),
            ],
            options={
                'verbose_name': 'Пункты мед.осмотра',
                'verbose_name_plural': 'Пункт мед.осмотра',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.TextField()),
                ('date_finish_education', models.DateField()),
                ('photo_education', models.ImageField(upload_to='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.employee')),
            ],
            options={
                'verbose_name': 'Образования',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_certificate', models.TextField()),
                ('date_finish_certificate', models.DateField()),
                ('date_end_certificate', models.DateField()),
                ('photo_certificate', models.ImageField(upload_to='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.employee')),
            ],
            options={
                'verbose_name': 'Удостоверения',
                'verbose_name_plural': 'Удостоверение',
            },
        ),
    ]
